name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 10
      uses: actions/setup-java@v2
      with:
        java-version: '10'
        distribution: 'temurin'
        cache: gradle
        
  
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: bash ./DuerOS-Launcher/build-app-headunit-portrait-open.sh
